# Generated by Django 4.2.6 on 2023-12-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role_name',
            field=models.CharField(default='Nhân viên y tế', max_length=50),
        ),
    ]
